<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CuteUtils" Version="1.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SharpOpenNat" Version="4.0.17" />
  </ItemGroup>

</Project>
